### ISSUE TITLE
No license information

### ISSUE THREAD

**Issue by asb** [hku-casr/riscv_overlay#1]
With no explicit license information, it's not clear how your implementation can be used. For example, the VectorBlox ORCA and Berkeley Z-scale implementations you reference both have BSD licenses:

https://github.com/VectorBlox/orca/blob/master/license.txt
https://github.com/ucb-bar/zscale/blob/master/LICENSE

I just saw your paper as it was posted to arXiv today, really impressive results. Are you going to be at the RISC-V Workshop next month? https://riscv.org/2016/06/4th-risc-v-workshop-prelim-agenda/

**Comment by hcng10** [comment]
Thank you very much for your interests in our design.

RISCV-Overlay comes with BSD license. Sorry that we did not upload the license file.

I am afraid that we will not be attending the RISC-V workshop next month.

**Comment by asb** [comment]
Fantastic, thanks for adding the license file.
